import { getPayload } from 'payload'
import config from '../payload.config'
import fs from 'fs'
import path from 'path'
import { customTranslations } from '../src/admin/i18n/custom-translations'

const ADMIN_KEY_PREFIXES = [
  'customHeader',
  'customSidebar',
  'customDashboard',
  'customCells',
  'customFields',
]

function isAdminKey(key: string) {
  return ADMIN_KEY_PREFIXES.some((prefix) => key === prefix || key.startsWith(`${prefix}.`))
}

function cloneTranslationTree(tree: Record<string, unknown>) {
  return JSON.parse(JSON.stringify(tree)) as Record<string, unknown>
}

function buildNestedTree(records: Array<{ key: string; vi: string; en: string }>, locale: 'vi' | 'en') {
  const tree: Record<string, unknown> = cloneTranslationTree(customTranslations[locale])

  for (const record of records) {
    if (!isAdminKey(record.key)) continue
    const value = record[locale]
    if (value === undefined || value === null) continue

    const parts = record.key.split('.')
    let current: Record<string, unknown> = tree

    for (let i = 0; i < parts.length; i++) {
      const part = parts[i]
      if (part === '__proto__' || part === 'constructor' || part === 'prototype') continue

      if (i === parts.length - 1) {
        current[part] = value
      } else {
        if (!current[part] || typeof current[part] !== 'object') {
          current[part] = Object.create(null)
        }
        current = current[part] as Record<string, unknown>
      }
    }
  }

  return tree
}

async function main() {
  process.env.PAYLOAD_MIGRATING = process.env.PAYLOAD_MIGRATING || 'true'

  const outputPath = path.resolve(process.cwd(), 'src/admin/i18n/generated-translations.ts')

  if (process.env.SKIP_ADMIN_TRANSLATION_GENERATION === 'true') {
    if (!fs.existsSync(outputPath)) {
      throw new Error(`Cannot skip admin translation generation because ${outputPath} does not exist`)
    }
    console.log(`Skipped admin translation generation; using existing ${outputPath}`)
    return
  }

  const payload = await getPayload({ config })

  const result = await payload.find({
    collection: 'translations',
    limit: 1000,
    depth: 0,
    pagination: false,
  })

  const records = result.docs as unknown as Array<{ key: string; vi: string; en: string }>

  const vi = buildNestedTree(records, 'vi')
  const en = buildNestedTree(records, 'en')

  const fileContent = `// Auto-generated by scripts/generate-admin-translations.ts
// Do not edit manually.

export const generatedTranslations = {
  vi: ${JSON.stringify(vi, null, 2)},
  en: ${JSON.stringify(en, null, 2)},
} as const
`

  fs.writeFileSync(outputPath, fileContent, 'utf-8')
  console.log(`Generated ${outputPath} (${records.length} total records)`)
}

main()
  .then(() => process.exit(0))
  .catch((err) => {
    console.error('Failed to generate admin translations:', err)
    process.exit(1)
  })
